### ISSUE TITLE
Crash when seeing other peer.

### ISSUE THREAD

**Issue by vi** [js-labs/WalkieTalkie#36]
```02-07 20:11:53.953 20584 20620 I Channel : Channel_00: connected to [Q2hhbm5lbF8wMA:MCMEkIs6c0M:] /192.168.112.102:47418
02-07 20:11:53.993 20584 20616 E AndroidRuntime: FATAL EXCEPTION: CTP-22900
02-07 20:11:53.993 20584 20616 E AndroidRuntime: Process: org.jsl.wfwt, PID: 20584
02-07 20:11:53.993 20584 20616 E AndroidRuntime: java.lang.ExceptionInInitializerError
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.wfwt.AudioPlayer.create(AudioPlayer.java:279)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.wfwt.HandshakeClientSession.onDataReceived(HandshakeClientSession.java:138)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.collider.SocketChannelReader.handleData(SocketChannelReader.java:285)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.collider.SocketChannelReader.runInThreadPool(SocketChannelReader.java:507)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.collider.ThreadPool$Worker.run(ThreadPool.java:95)
02-07 20:11:53.993 20584 20616 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.jsl.wfwt.AudioPlayer can not access a member of class org.jsl.wfwt.AudioPlayer$Impl with modifiers "private volatile"
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:348)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:109)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at org.jsl.wfwt.AudioPlayer.<clinit>(AudioPlayer.java:41)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        ... 5 more
02-07 20:11:53.993 20584 20616 E AndroidRuntime: Caused by: java.lang.IllegalAccessException: Class org.jsl.wfwt.AudioPlayer can not access a member of class org.jsl.wfwt.AudioPlayer$Impl with modifiers "private volatile"
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:125)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at sun.reflect.misc.ReflectUtil.ensureMemberAccess(ReflectUtil.java:100)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:330)
02-07 20:11:53.993 20584 20616 E AndroidRuntime:        ... 7 more
02-07 20:11:54.002  1443 20624 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-07 20:11:54.003  1443  3790 W ActivityTaskManager:   Force finishing activity org.jsl.wfwt/.MainActivity```

Running Android 11.

**Comment by js-labs** [comment]
Hi!
Thank you for feedback.
Where did you got the app binary?
